import { Inter } from 'next/font/google';
import Header from '@/components/header';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <body className={inter.className}>
      <Header />
      {children}
    </body>
  </html>
);

export default RootLayout;
